print("append()\n original list")
print("\r")
animals=['dog','cat','cow']
print(animals)
print("\r")
print("after appending")
animals.append('rabbit')
print(animals)
print("\r")
print("clear()")
print("\r")
animals.clear()
print("after clearing")
print("animals:")
print("\r")
print("count()")
print("\r")
print("append()\n original list")
animal=['dog','cat','cow','horse','cow']
print(animal)
print("how many cow's are there")
count=animal.count('cow')
print("after counting")
print("count: ",count)
print("extend()")
print("\r")
other=['elephant']
print("after extending")
animal.extend(other)
print(animal)
print("\r")
print("index()")
print("\r")
index=animal.index('horse')
print("index of horse is : ",index)
print("\r")
print("insert()")
print("\r")
animal.insert(2,'deer')
print("after extending")
print(animal)
print("\r")
print("pop()")
print("\r")
animal.pop(3)
print("after poping")
print(animal)
print("\r")
print("remove()")
print("\r")
animal.remove('cow')
print("after removing")
print(animal)
print("\r")
print("reverse()")
print("\r")
animal.reverse()
print("after reversing")
print(animal)
print("\r")
print("sort()")
print("\r")
animal.sort()
print("after sorting")
print(animal)
print("\r")
