values=(1,2,3,4,5,'one','two,','three','four')
print("\n")
print(values)
print("Positive indexing")
print(values[2])
print("\n")
print("Slicing")
print(values[2:5])
print("\n")
print("Negative indexing")
print(values[-2])
print("\n")
print("Slicing")
print(values[-5:-2])
print("\n")
print("Concatenation")
print("Tuples are as follows")
tuple1=(1,2,3,4)
tuple2=(5,6,7,8)
print("\n")
print(tuple1)
print(tuple2)
tuple3=(tuple1+tuple2)
print("Concatenated result")
print(tuple3)
print("\n")
print("Multiplid tuple")
tuple4=tuple1*2
print(tuple4)
print("\n")
print("Tuple Functions")
print("length of first tuple is ",len(values))
print("\n")
print("Maximum value of second tuple is ",max(tuple1))
print("\n")
print("Minimum value of second tuple is ",min(tuple1))
print("\n")

