name=input("Enter your name : ")
age=int(input("Enter your age : "))
company=input("Enter your company name : ")
designation=input("Enter your Designation : ")

fp=open("sample4.txt","w")
fp.write("Name : %s" % name)
fp.write("\n Age : %d" % age)
fp.write("\n Company : %s" % company)
fp.write("\n Designation : %s" % designation)
fp.close()