a=int(input("Enter the first number: "))
b=int(input("Enter the second number : "))
fp=open("sample1.txt","w")
fp.write("The first  number is %d " %(a))
fp.write("\n The second number is %d " %(b))
fp.write("\n %d+%d=%d"%(a,b,a+b))
fp.write("\n %d-%d=%d"%(a,b,a-b))
fp.write("\n %d*%d=%d"%(a,b,a*b))
fp.write("\n %d/%d=%d"%(a,b,a/b))
fp.write("\n %d//%d=%d"%(a,b,a//b))
fp.close()
